# Generated by Django 6.0.7 on 2026-07-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_following_artistprofile_usersettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='system_voice',
            field=models.CharField(choices=[('en-is', 'English'), ('fa', 'Persian')], default='en-is', max_length=20),
        ),
    ]
