# Generated by Django 6.0.7 on 2026-07-28 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_following_artistprofile_usersettings_and_more'),
        ('albums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField()),
                ('track_number', models.PositiveIntegerField(default=1)),
                ('streams', models.PositiveIntegerField(db_index=True, default=0)),
                ('audio_file', models.FileField(upload_to='songs/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('release_date', models.DateTimeField(db_index=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='accounts.artistprofile')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_songs', to='accounts.artistprofile')),
                ('genre', models.ManyToManyField(blank=True, null=True, related_name='songs', to='albums.genre')),
            ],
            options={
                'ordering': ['track_number'],
            },
        ),
        migrations.CreateModel(
            name='PlayHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_history', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
            ],
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', '-release_date'], name='songs_song_artist__ee69d6_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['album', 'track_number'], name='songs_song_album_i_1a8da4_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-streams'], name='songs_song_streams_53283e_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['user', '-played_at'], name='songs_playh_user_id_62504b_idx'),
        ),
        migrations.AddIndex(
            model_name='playhistory',
            index=models.Index(fields=['song', '-played_at'], name='songs_playh_song_id_c00dee_idx'),
        ),
    ]
