# Generated by Django 6.0.7 on 2026-08-03 13:54

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to=songs.models.song_audio_upload_path),
        ),
    ]
