# Generated by Django 6.0.7 on 2026-07-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold')], default='basic', max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('daily_stream_limit', models.PositiveIntegerField(default=60)),
                ('playlist_limit', models.PositiveIntegerField(default=6)),
                ('profile_picture_upload', models.BooleanField(default=False)),
                ('song_download', models.BooleanField(default=False)),
                ('early_access', models.BooleanField(default=False)),
                ('stats_info', models.BooleanField(default=False)),
            ],
        ),
    ]
