# Generated by Django 6.0.7 on 2026-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='daily_stream_limit',
            field=models.PositiveIntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='playlist_limit',
            field=models.PositiveIntegerField(blank=True, default=6, null=True),
        ),
    ]
