# Generated by hand: add duration_months to SubscriptionTransaction
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_subscriptiontransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontransaction",
            name="duration_months",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
