# Generated by Django 6.0.7 on 2026-08-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_initial'),
        ('songs', '0002_alter_song_genre'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(fields=('playlist', 'position'), name='unique_playlist_position'),
        ),
    ]
