# Generated by Django 6.0.7 on 2026-08-03 13:54

import playlists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlistitem_unique_playlist_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=playlists.models.playlist_cover_upload_path),
        ),
    ]
