# Generated by Django 6.0.7 on 2026-07-28 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_user_following_artistprofile_usersettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_single', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField(db_index=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='accounts.artistprofile')),
                ('collaborators', models.ManyToManyField(blank=True, related_name='collaborated_albums', to='accounts.artistprofile')),
                ('genre', models.ManyToManyField(blank=True, null=True, related_name='albums', to='albums.genre')),
            ],
            options={
                'indexes': [models.Index(fields=['artist', '-release_date'], name='albums_albu_artist__c520fc_idx')],
            },
        ),
    ]
