# Generated by Django 6.0.7 on 2026-07-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='albums', to='albums.genre'),
        ),
    ]
