# Generated by Django 6.0.7 on 2026-08-03 13:54

import albums.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_alter_album_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=albums.models.album_cover_upload_path),
        ),
    ]
